apiVersion: v1
kind: Service
metadata:
  annotations:
  creationTimestamp: null
  labels:
    app: prestashop
  name: prestashop
spec:
  clusterIP: None
  ports:
    - name: "80"
      port: 80
      targetPort: 80    
  selector:
    app: prestashop
status:
  loadBalancer: {}
